# Generated by Django 5.2.13 on 2026-04-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_camera_alter_violation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='violation_type',
            field=models.CharField(choices=[('no_helmet', 'No Helmet'), ('no_seatbelt', 'No Seatbelt'), ('red_light', 'Red Light'), ('over_speed', 'Over Speed'), ('illegal_parking', 'Illegal Parking'), ('other', 'Other')], default='no_helmet', max_length=32),
        ),
    ]
